# I modified the github action from @arichornlover 's uYouEnhanced repo, but the original idea is by @ISnackable. Thanks to both of them!
# https://github.com/ISnackable/YTCubePlus/blob/main/.github/workflows/Build.yml

name: Inject Deb Into IPA
on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: "iOS SDK version to be used during build (don't change it if you don't know what you are doing)"
        default: "16.2"
        required: true
        type: string  
        
      decrypted_ipa_url:
        description: "The direct URL to the decrypted YouTube ipa (I recommend using Dropbox, Google Drive is causing errors)"
        default: "https://iosmod.net/IPAs/YouTube_19.23.3.ipa"
        required: true
        type: string
        
      deb1_url:
        description: "The direct URL to the Tweak deb 1"
        default: "https://iosmod.net/deb/com.iosmod.youtubepremium_1.6.6_iphoneos-arm.deb"
        required: false
        type: string
      deb1_url_choose:
        description: "Using Deb 1"
        default: true
        required: false
        type: boolean

      deb2_url:
        description: "The direct URL to the Tweak deb 2"
        default: "https://iosmod.net/deb/com.ps.youpip_1.8.10_iphoneos-arm.deb"
        required: false
        type: string
      deb2_url_choose:
        description: "Using Deb 2"
        default: false
        required: false
        type: boolean
        
      deb3_url:
        description: "The direct URL to the Tweak deb 3"
        default: "https://iosmod.net/deb/com.ps.youpip_1.8.10_iphoneos-arm.deb"
        required: false
        type: string
      deb3_url_choose:
        description: "Using Deb 3"
        default: false
        required: false
        type: boolean
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Inject Deb Into IPA
    runs-on: macos-12
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make
              

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH 

      - name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          ref: 4bcc52914e0eeca719288522938185decaa8a1cb
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.1
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/thaibm92/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS${{ inputs.sdk_version }}.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.1
        with:
          repository: qnblackcat/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos
          
      - name: Install Azule
        run: |
          cd ${{ github.workspace }}/main
          git clone https://github.com/Al4ise/Azule 
          sudo ln -sf ~/Azule/azule /usr/local/bin/azule

      - name: Downloading IPA
        run: |
          wget "$IPA_URL" --no-verbose -O main/IPA.ipa
        env:
          IPA_URL: ${{ inputs.decrypted_ipa_url }}
      
      - name: Downloading DEB1
        if: ${{ inputs.deb1_url_choose }}
        run: |
          wget "$DEB1_URL" --no-verbose -O main/packages/DEB1.deb
        env:
          DEB1_URL: ${{ inputs.deb1_url }}
      
      - name: Downloading DEB2
        if: ${{ inputs.deb2_url_choose }}
        run: |
          wget "$DEB2_URL" --no-verbose -O main/packages/DEB2.deb
        env:
          DEB2_URL: ${{ inputs.deb2_url }}
      
      - name: Downloading DEB3
        if: ${{ inputs.deb3_url_choose }}
        run: |
          wget "$DEB3_URL" --no-verbose -O main/packages/DEB3.deb
        env:
          DEB3_URL: ${{ inputs.deb3_url }}  
          
      - name: Build DEB_FILES variable
        run: |
          DEB_FILES=""
          if [[ -f "main/packages/DEB1.deb" ]]; then DEB_FILES="$DEB_FILES -f $PWD/main/packages/DEB1.deb"; fi
          if [[ -f "main/packages/DEB2.deb" ]]; then DEB_FILES="$DEB_FILES -f $PWD/main/packages/DEB2.deb"; fi
          if [[ -f "main/packages/DEB3.deb" ]]; then DEB_FILES="$DEB_FILES -f $PWD/main/packages/DEB3.deb"; fi
          echo "DEB_FILES=$DEB_FILES" >> $GITHUB_ENV
      
      - name: Inject tweak into provided IPA
        run: |
          brew install coreutils
          cd ${{ github.workspace }}/main
          ./Azule/azule -i $PWD/main/IPA.ipa -o $PWD/main/packages/IPA_OUT.ipa ${{ env.DEB_FILES }}

      - name: Remove the Watch folder
        run: |
          cd ${{ github.workspace }}/main/packages
          mv YouTubePremium.ipa YouTubePremium.zip
          unzip YouTubePremium.zip
          cd Payload/YouTube.app
          rm -rf Watch
          cd ../..
          zip -r YouTube_Premium_.ipa Payload
          rm -rf Payload    

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.1
        with:
          tag_name: v${{ github.run_number }}
          name: v${{ github.run_number }}
          files: main/packages/*.ipa
          draft: true
